[package]
name = "bevy_tasks"
version = "0.11.0-dev"
edition = "2021"
description = "A task executor for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
futures-lite = "1.13"
async-executor = "1.5"
async-channel = "1.4.2"
async-task = "4.2.0"
concurrent-queue = "2.0.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[dev-dependencies]
web-time = { version = "0.2" }
