[package]
name = "bevy_color_blindness"
version = "0.9.0-dev"
edition = "2021"
description = "Provides color blindness simulation for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.9.0-dev" }
bevy_asset = { path = "../bevy_asset", version = "0.9.0-dev" }
bevy_core_pipeline = { path = "../bevy_core_pipeline", version = "0.9.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.9.0-dev" }
bevy_math = { path = "../bevy_math", version = "0.9.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.9.0-dev", features = [
    "bevy",
] }
bevy_render = { path = "../bevy_render", version = "0.9.0-dev" }
bevy_sprite = { path = "../bevy_sprite", version = "0.9.0-dev" }
bevy_transform = { path = "../bevy_transform", version = "0.9.0-dev" }
bevy_ui = { path = "../bevy_ui", version = "0.9.0-dev" }
bevy_window = { path = "../bevy_window", version = "0.9.0-dev" }

[dev-dependencies]
bevy_input = { path = "../bevy_input", version = "0.9.0-dev" }
